[package]
name = "idchoppers"
version = "0.1.0"
authors = ["Eevee (Lexy Munroe) <eevee.git@veekun.com>"]

[dependencies]
error-chain = "0.10.0"
svg = "0.5.5"

[dependencies.nom]
version = "^2.1"
features = ["verbose-errors"]
